= Atomic Host Demo


== Add the image (avoid auto-download)

To avoid download time, add the box using a local image.

.Add Atomic Vagrant Box (VirtualBox)
----
vagrant box add --name atomic-f26 \
  Fedora-Atomic-Vagrant-26-1.5.x86_64.vagrant-virtualbox.box
----

== Install the Atomic Vagrant Configuration

Clone the git repository with this text and the vagrant configuration
for the Atomic Host lab.

.Prepare Atomic Vagrant
----
git clone https://github.com/markllama/lisa17
cd lisa17/atomic-vagrant
export VAGRANT_DEFAULT_PROVIDER=virtualbox
----

== Start the instances

[subs=+macros]
.Start Atomic Cluster
----
$ +vagrant status+
Current machine states:

atomic-01                 not created (virtualbox)
atomic-02                 not created (virtualbox)
atomic-03                 not created (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run 'vagrant status NAME'.
$ +vagrant up+
----

Once the instances are up, create three windows using tabs, or tmux and log in to the first one.

.Login to an instnace in Vagrant
----
vagrant ssh atomic-01
----

Log into _atomic-02_ and _atomic-03_ in the same way.


== Configure `etcd`

A template for the `etcd.conf` is provided in `sync/etcd.conf.template`. A simple `sed` line will replace the values needed for each host.

.etcd.conf.template
----
# [member]
ETCD_NAME=atomic-0{HOSTNUM}
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"

ETCD_LISTEN_PEER_URLS="http://172.17.8.10{HOSTNUM}:2380"
ETCD_LISTEN_CLIENT_URLS="http://127.0.0.1:2379,http://172.17.8.10{HOSTNUM}:2379"

# [cluster]
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://172.17.8.10{HOSTNUM}:2380"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_ADVERTISE_CLIENT_URLS="http://172.17.8.10{HOSTNUM}:2379"

ETCD_INITIAL_CLUSTER="atomic-01=http://172.17.8.101:2380,atomic-02=http://172.17.8.102:2380,atomic-03=http://172.17.8.103:2380"

#[security]
#ETCD_CERT_FILE=""
#ETCD_KEY_FILE=""
#ETCD_CLIENT_CERT_AUTH="false"
#ETCD_TRUSTED_CA_FILE=""
#ETCD_AUTO_TLS="false"
#ETCD_PEER_CERT_FILE=""
#ETCD_PEER_KEY_FILE=""
#ETCD_PEER_CLIENT_CERT_AUTH="false"
#ETCD_PEER_TRUSTED_CA_FILE=""
#ETCD_PEER_AUTO_TLS="false"
----

In this simple environment you only need to set the host number in the member and cluster sections.  We're ignoring security for this lab.

To prepare and start the `etcd` on the first instance, run the command below.
The `systemctl start` will block waiting to form a cluster.

.Configure etcd 1
----
sed 's/{HOSTNUM}/1/' sync/etcd.conf.template > etcd.conf
sudo cp etcd.conf /etc/etcd/
sudo systemctl start etcd
----

Note the `HOSTUM` replacement.  Do the same thing on _atomic-02_ and
_atomic-03_ as well, replacint "1" with "2" and "3" for each host.


.Configure etcd 2 and 3
----
sed 's/{HOSTNUM}/2/' sync/etcd.conf.template > etcd.conf
sudo cp etcd.conf /etc/etcd/
sudo systemctl start etcd
----

When you start the second etcd, the cluster will begin to form and the
first systemctl will unblock and complete.  When automating, if sync
is not needed, add the `--no-block` switch to proceed.

When all three are started, check the status of the cluster with the `etcdctl member list` command.

----
etcdctl member list
25d6ce33763c5524: name=atomic-02 peerURLs=http://172.17.8.102:2380 clientURLs=http://172.17.8.102:2379 isLeader=false
6ae27f9fa2984b1d: name=atomic-01 peerURLs=http://172.17.8.101:2380 clientURLs=http://172.17.8.101:2379 isLeader=true
ff32f4b39b9c47bd: name=atomic-03 peerURLs=http://172.17.8.103:2380 clientURLs=http://172.17.8.103:2379 isLeader=false
----

== Verify and Explore `etcd` operation

Add a key/value to the etcd database.  Run the add operation on _atomic-01_

----

[vagrant@atomic-01 ~]$ etcdctl set /test/value '{"test": "value0"}'{"test": "value0"}
----

The key and value should be visible from all three hosts.

----
[vagrant@atomic-03 ~]$ etcdctl get /test/value
{"test": "value0"}
----

Set, get and update keys this way.

Etcd can also block waiting for changes or _watching_ on a key.

On _atomic-03_ watch the `/test/value` key.

----
[vagrant@atomic-03 ~]$ etcdctl watch /test/value # blocks
----

Set a new value from _atomic_02_.

----
[vagrant@atomic-02 ~]$ etcdctl set /test/value '{"test": "value1"}'
{"test": "value1"}
----

The client on _atomic-03_ unblocks and returns the new value.

----
[vagrant@atomic-03 ~]$ etcdctl watch /test/value # unblocked
{"test": "value1"}
----
== Configure Flannel SDN



=== Vagrant Boxes

* https://dl.fedoraproject.org/pub/fedora/linux/releases/26/CloudImages/x86_64/images/Fedora-Atomic-Vagrant-26-1.5.x86_64.vagrant-virtualbox.box[Fedora 26 Virtualbox image]
* https://dl.fedoraproject.org/pub/fedora/linux/releases/26/CloudImages/x86_64/images/Fedora-Atomic-Vagrant-26-1.5.x86_64.vagrant-libvirt.box[Fedora 26 libvirt image]





